package jm.org.bysj.db.gdao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import jm.org.bysj.db.ImageLogsModels;
import jm.org.bysj.db.LogsDetailsModels;

import jm.org.bysj.db.gdao.ImageLogsModelsDao;
import jm.org.bysj.db.gdao.LogsDetailsModelsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig imageLogsModelsDaoConfig;
    private final DaoConfig logsDetailsModelsDaoConfig;

    private final ImageLogsModelsDao imageLogsModelsDao;
    private final LogsDetailsModelsDao logsDetailsModelsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        imageLogsModelsDaoConfig = daoConfigMap.get(ImageLogsModelsDao.class).clone();
        imageLogsModelsDaoConfig.initIdentityScope(type);

        logsDetailsModelsDaoConfig = daoConfigMap.get(LogsDetailsModelsDao.class).clone();
        logsDetailsModelsDaoConfig.initIdentityScope(type);

        imageLogsModelsDao = new ImageLogsModelsDao(imageLogsModelsDaoConfig, this);
        logsDetailsModelsDao = new LogsDetailsModelsDao(logsDetailsModelsDaoConfig, this);

        registerDao(ImageLogsModels.class, imageLogsModelsDao);
        registerDao(LogsDetailsModels.class, logsDetailsModelsDao);
    }
    
    public void clear() {
        imageLogsModelsDaoConfig.clearIdentityScope();
        logsDetailsModelsDaoConfig.clearIdentityScope();
    }

    public ImageLogsModelsDao getImageLogsModelsDao() {
        return imageLogsModelsDao;
    }

    public LogsDetailsModelsDao getLogsDetailsModelsDao() {
        return logsDetailsModelsDao;
    }

}
