package jm.org.bysj.db.gdao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import jm.org.bysj.db.LogsDetailsModels;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LOGS_DETAILS_MODELS".
*/
public class LogsDetailsModelsDao extends AbstractDao<LogsDetailsModels, Long> {

    public static final String TABLENAME = "LOGS_DETAILS_MODELS";

    /**
     * Properties of entity LogsDetailsModels.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ImageName = new Property(1, String.class, "imageName", false, "IMAGE_NAME");
        public final static Property TagName = new Property(2, String.class, "tagName", false, "TAG_NAME");
        public final static Property TagDetail = new Property(3, String.class, "tagDetail", false, "TAG_DETAIL");
    }


    public LogsDetailsModelsDao(DaoConfig config) {
        super(config);
    }
    
    public LogsDetailsModelsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LOGS_DETAILS_MODELS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"IMAGE_NAME\" TEXT," + // 1: imageName
                "\"TAG_NAME\" TEXT," + // 2: tagName
                "\"TAG_DETAIL\" TEXT);"); // 3: tagDetail
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LOGS_DETAILS_MODELS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, LogsDetailsModels entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String imageName = entity.getImageName();
        if (imageName != null) {
            stmt.bindString(2, imageName);
        }
 
        String tagName = entity.getTagName();
        if (tagName != null) {
            stmt.bindString(3, tagName);
        }
 
        String tagDetail = entity.getTagDetail();
        if (tagDetail != null) {
            stmt.bindString(4, tagDetail);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, LogsDetailsModels entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String imageName = entity.getImageName();
        if (imageName != null) {
            stmt.bindString(2, imageName);
        }
 
        String tagName = entity.getTagName();
        if (tagName != null) {
            stmt.bindString(3, tagName);
        }
 
        String tagDetail = entity.getTagDetail();
        if (tagDetail != null) {
            stmt.bindString(4, tagDetail);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public LogsDetailsModels readEntity(Cursor cursor, int offset) {
        LogsDetailsModels entity = new LogsDetailsModels( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // imageName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // tagName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // tagDetail
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, LogsDetailsModels entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setImageName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTagName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTagDetail(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(LogsDetailsModels entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(LogsDetailsModels entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(LogsDetailsModels entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
